# Generated by Django 4.0.1 on 2022-01-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_allergy_image_size_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='drink',
        ),
    ]
