# Generated by Django 4.0.1 on 2022-01-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_allergy_id_allergy_drink_allergy_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='size',
            table='sizes',
        ),
    ]
